######################################
#
#   Horse Guard by Shantek
#
#   Want the breaking edge stuff, you can find dev builds here:
#   https://shantek.dev/job/HorseGuard/
#
######################################

# Prefix of all messages sent to the player
message-prefix: "&7[&bHorse&6Guard&7] "