name: HorseGuard
version: 0.2.0
main: io.shantek.HorseGuard
api-version: 1.20
commands:
  horse:
    description: Manages horse trust
    usage: /horse <trust|untrust|trustlist> <playername>
    aliases: [htrust]

permissions:
  shantek.horseguard.ride:
    description: Allows the player to ride and lead any horse without ownership.
    default: op
  shantek.horseguard.damage:
    description: Allows the player to damage any horse without ownership.
    default: op

